#ifndef LAIN_TYPE_INTERGER_8_SIGNED_OVERFLOWAWARE_OPERATION_COMPARISON_NOTEQUALTO_H
#define LAIN_TYPE_INTERGER_8_SIGNED_OVERFLOWAWARE_OPERATION_COMPARISON_NOTEQUALTO_H

#include "lain.type.integer.8.signed.overflowAware.operation.comparison.typedef.h"

lain_type_integer_8_signed_overflowAware_operation_comparison lain_type_integer_8_signed_overflowAware_operation_comparison_notEqualTo;

#endif