#ifndef LAIN_TYPE_INTERGER_8_SIGNED_OPERATION_COMPARISON_BYTHREAD_TYPEDEF_H
#define LAIN_TYPE_INTERGER_8_SIGNED_OPERATION_COMPARISON_BYTHREAD_TYPEDEF_H

#include "lain.type.integer.8.signed.operation.comparison.byThread.argument.pointer.typedef.h"

typedef void lain_type_integer_8_signed_operation_comparison_byThread_type(lain_type_integer_8_signed_operation_comparison_byThread_argument_pointer);

#endif