#ifndef LAIN_TYPE_INTERGER_8_SIGNED_OPERATION_COMPARISON_BYPOINTER_H
#define LAIN_TYPE_INTERGER_8_SIGNED_OPERATION_COMPARISON_BYPOINTER_H

#include "lain.type.integer.8.signed.operation.comparison.byPointer.typedef.h"

lain_type_integer_8_signed_operation_comparison_byPointer_type lain_type_integer_8_signed_operation_comparison_byPointer;

#endif