#ifndef LAIN_TYPE_INTERGER_8_SIGNED_OPERATION_TERNARY_TERNARY_TYPEDEF_H
#define LAIN_TYPE_INTERGER_8_SIGNED_OPERATION_TERNARY_TERNARY_TYPEDEF_H

#include "lain.type.integer.8.signed.typedef.h"

lain_type_integer_8_signed_operation_ternary lain_type_integer_8_signed_operation_ternary(lain_type_integer_8_signed left, lain_type_integer_8_signed ifTrue, lain_type_integer_8_signed ifFalse);

#endif