#ifndef LAIN_TYPE_INTEGER_8_SIGNED_POINTER_FROM_LAIN_TYPE_INTEGER_8_SIGNED_H
#define LAIN_TYPE_INTEGER_8_SIGNED_POINTER_FROM_LAIN_TYPE_INTEGER_8_SIGNED_H

#include "lain.type.integer.8.signed.pointer.from.lain.type.integer.8.signed.typedef.h"

lain_type_integer_8_signed_pointer_from_lain_type_integer_8_signed_type lain_type_integer_8_signed_pointer_from_lain_type_integer_8_signed;

#endif