#ifndef LAIN_TYPE_INTERGER_8_SIGNED_OPERATION_COMPARISON_BYTHREAD_H
#define LAIN_TYPE_INTERGER_8_SIGNED_OPERATION_COMPARISON_BYTHREAD_H

#include "lain.type.integer.8.signed.operation.comparison.byThread.typedef.h"

lain_type_integer_8_signed_operation_comparison_byThread_type lain_type_integer_8_signed_operation_comparison_byThread;


#endif