#ifndef LAIN_C_CHAR_SIGNED_CONSTANT_BOUNDRY_UPPER_H
#define LAIN_C_CHAR_SIGNED_CONSTANT_BOUNDRY_UPPER_H
extern const long lain_c_char_signed_constant_boundry_upper;
#endif /*LAIN_C_CHAR_SIGNED_CONSTANT_BOUNDRY_UPPER_H*/