#ifndef LAIN_C_CHAR_SIGNED_CONSTANT_WIDTH_BYTE_H
#define LAIN_C_CHAR_SIGNED_CONSTANT_WIDTH_BYTE_H
extern const long lain_c_char_signed_constant_width_byte;
#endif /*LAIN_C_CHAR_SIGNED_CONSTANT_WIDTH_BYTE_H*/