#ifndef LAIN_TYPE_INTERGER_8_SIGNED_OPERATION_COMPARISON_BYTHREAD_ARGUMENT_NEW_TYPEDEF_H
#define LAIN_TYPE_INTERGER_8_SIGNED_OPERATION_COMPARISON_BYTHREAD_ARGUMENT_NEW_TYPEDEF_H

#include "lain.type.integer.8.signed.operation.comparison.byThread.argument.typedef.h"
#include "lain.type.integer.8.signed.operation.comparison.pointer.typedef.h"
#include "lain.type.integer.8.signed.pointer.typedef.h"

typedef lain_type_integer_8_signed_operation_comparison_byThread_argument lain_type_integer_8_signed_operation_comparison_byThread_argument_new_type(lain_type_integer_8_signed, lain_type_integer_8_signed, lain_type_integer_8_signed_pointer, lain_type_integer_8_signed_operation_comparison_pointer);


#endif