#ifndef LAIN_C_CHAR_SIGNED_OPERATION_COMPARISON_BITWISEXOR_H
#define LAIN_C_CHAR_SIGNED_OPERATION_COMPARISON_BITWISEXOR_H

#include "lain.c.char.signed.operation.comparison.typedef.h"

lain_c_char_signed_operation_comparison lain_c_char_signed_operation_comparison_bitwiseXOr;
#endif /*LAIN_C_CHAR_SIGNED_OPERATION_COMPARISON_BITWISEXOR_H*/