#ifndef LAIN_C_CHAR_SIGNED_OPERATION_MAP_SIGNNEGATE_H
#define LAIN_C_CHAR_SIGNED_OPERATION_MAP_SIGNNEGATE_H

#include "lain.c.char.signed.operation.map.typedef.h"

lain_c_char_signed_operation_map lain_c_char_signed_operation_map_signNegate;
#endif /*LAIN_C_CHAR_SIGNED_OPERATION_MAP_SIGNNEGATE_H*/