#ifndef LAIN_C_CHAR_SIGNED_OPERATION__OVERFLOWAWARE_OPERATION_CONSTRUCT_TYPEDEF_H
#define LAIN_C_CHAR_SIGNED_OPERATION__OVERFLOWAWARE_OPERATION_CONSTRUCT_TYPEDEF_H

#include "lain.c.char.signed.operation..overflowAware.return.typedef.h"

typedef lain_c_char_signed_operation__overflowAware_return lain_c_char_signed_operation__overflowAware_operation_construct_type(lain_c_char_signed, lain_c__operation__overflowAware_return_state);

#endif /*LAIN_C_CHAR_SIGNED_OPERATION__OVERFLOWAWARE_OPERATION_CONSTRUCT_TYPEDEF_H*/