#ifndef LAIN_TYPE_INTERGER_8_SIGNED_OPERATION__OVERFLOWAWARE_OPERATION_CONSTRUCT_H
#define LAIN_TYPE_INTERGER_8_SIGNED_OPERATION__OVERFLOWAWARE_OPERATION_CONSTRUCT_H

#include "lain.type.integer.8.signed.operation..overflowAware.operation.construct.typedef.h"

lain_type_integer_8_signed_operation__overflowAware_operation_construct_type lain_type_integer_8_signed_operation__overflowAware_operation_construct;

#endif