#ifndef LAIN_TYPE_INTERGER_8_SIGNED_OPERATION_MAP_TYPEDEF_H
#define LAIN_TYPE_INTERGER_8_SIGNED_OPERATION_MAP_TYPEDEF_H

#include "lain.type.integer.8.signed.typedef.h"

typedef lain_type_integer_8_signed lain_type_integer_8_signed_operation_map(lain_type_integer_8_signed);

#endif