#ifndef LAIN_TYPE_INTERGER_8_SIGNED_OPERATION_COMPARISON_ADD_H
#define LAIN_TYPE_INTERGER_8_SIGNED_OPERATION_COMPARISON_ADD_H

#include "lain.type.integer.8.signed.operation.comparison.typedef.h"

lain_type_integer_8_signed_operation_comparison lain_type_integer_8_signed_operation_comparison_add;

#endif