#ifndef LAIN_C_CHAR_SIGNED_OPERATION_MAP_SIGNABSOLUTE_H
#define LAIN_C_CHAR_SIGNED_OPERATION_MAP_SIGNABSOLUTE_H

#include "lain.c.char.signed.operation.map.typedef.h"

lain_c_char_signed_operation_map lain_c_char_signed_operation_map_signAbsolute;
#endif /*LAIN_C_CHAR_SIGNED_OPERATION_MAP_SIGNABSOLUTE_H*/