#ifndef LAINT_C_TYPE_SIZE
#define LAINT_C_TYPE_SIZE

#define C_TYPE_SIZE_CHAR 1
#define C_TYPE_SIZE_SHORT 2
#define C_TYPE_SIZE_INT 4
#define C_TYPE_SIZE_LONG 8
#define C_TYPE_SIZE_FLOAT 4
#define C_TYPE_SIZE_DOUBLE 8
#define C_TYPE_SIZE_SIZE_T 8

#endif