#ifndef LAIN_TYPE_INTEGER_8_SIGNED_OVERFLOWAWARE_OPERATION_CONSTRUCT_TYPEDEF_H
#define LAIN_TYPE_INTEGER_8_SIGNED_OVERFLOWAWARE_OPERATION_CONSTRUCT_TYPEDEF_H

#include "lain.type.integer.8.signed.overflowAware.typedef.h"

typedef lain_type_integer_8_signed_overflowAware lain_type_integer_8_signed_overflowAware_operation_construct_type(lain_type_integer_8_signed,lain_type_integer_8_signed);

#endif