#ifndef LAIN_TYPE_INTERGER_8_SIGNED_OPERATION_MAP_SQUARE_H
#define LAIN_TYPE_INTERGER_8_SIGNED_OPERATION_MAP_SQUARE_H

#include "lain.type.integer.8.signed.operation.map.typedef.h"

lain_type_integer_8_signed_operation_map lain_type_integer_8_signed_operation_map_square;

#endif