#ifndef LAIN_C_CHAR_SIGNED_OPERATION_MAP__OVERFLOWAWARE_TYPEDEF_H
#define LAIN_C_CHAR_SIGNED_OPERATION_MAP__OVERFLOWAWARE_TYPEDEF_H

#include "lain.c.char.signed.operation..overflowAware.return.typedef.h"

typedef lain_c_char_signed_operation__overflowAware_return (lain_c_char_signed_operation_map__overflowAware)(lain_c_char_signed);
#endif /*LAIN_C_CHAR_SIGNED_OPERATION_MAP__OVERFLOWAWARE_TYPEDEF_H*/