#include "lain.type.integer.8.signed.operation.map.signNegate.overflowAware.h"

lain_type_integer_8_signed_operation__overflowAware_return lain_type_integer_8_signed_operation_map_signNegate_overflowAware_return_overflow = {0,LAIN_TYPE_INTEGER__OPERATION__OVERFLOWAWARE_OVERFLOW};

lain_type_integer_8_signed_operation__overflowAware_return lain_type_integer_8_signed_operation_map_signNegate_overflowAware(lain_type_integer_8_signed arg){
    return arg!=LAIN_TYPE_INTEGER_8_SIGNED_CONSTANTS_BOUNDRY_LOW ? lain_type_integer_8_signed_operation__overflowAware_operation_construct(-arg,LAIN_TYPE_INTEGER__OPERATION__OVERFLOWAWARE_NO_OVERFLOW) : lain_type_integer_8_signed_operation_map_signNegate_overflowAware_return_overflow;
}